# Generated by Django 2.2.9 on 2020-01-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures_ru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_ru',
            name='group_name',
            field=models.CharField(max_length=128, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='group_ru',
            name='group_type',
            field=models.CharField(choices=[('DG', 'Demir Gapylar'), ('AG', 'Agaç Gapylar'), ('MB', 'Mebeller'), ('DO', 'Demir Önümler'), ('BK', 'Beýlekiler')], max_length=2, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide1',
            field=models.TextField(verbose_name='Слайд1 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide2',
            field=models.TextField(verbose_name='Слайд2 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide3',
            field=models.TextField(verbose_name='Слайд3 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide4',
            field=models.TextField(verbose_name='Слайд4 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide5',
            field=models.TextField(verbose_name='Слайд5 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='description_slide6',
            field=models.TextField(verbose_name='Слайд6 Подробно'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide1',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд1'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide2',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд2'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide3',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд3'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide4',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд4'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide5',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд5'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='img_slide6',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Слайд6'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='property1',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon1'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='property2',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon2'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='property3',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon3'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_property1',
            field=models.TextField(verbose_name='Услуга1'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_property2',
            field=models.TextField(verbose_name='Услуга2'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_property3',
            field=models.TextField(verbose_name='Услуга3'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide1',
            field=models.CharField(max_length=32, verbose_name='Слайд1 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide2',
            field=models.CharField(max_length=32, verbose_name='Слайд2 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide3',
            field=models.CharField(max_length=32, verbose_name='Слайд3 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide4',
            field=models.CharField(max_length=32, verbose_name='Слайд4 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide5',
            field=models.CharField(max_length=32, verbose_name='Слайд5 текст'),
        ),
        migrations.AlterField(
            model_name='main_page_ru',
            name='text_slide6',
            field=models.CharField(max_length=32, verbose_name='Слайд6 текст'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='is_new',
            field=models.BooleanField(default=0, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='product_description',
            field=models.TextField(verbose_name='Подробно'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furnitures_ru.Group_ru', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='product_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product_ru',
            name='product_name',
            field=models.CharField(max_length=128, verbose_name='Имя продукта'),
        ),
    ]
