# Generated by Django 2.2.9 on 2020-01-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128)),
                ('group_type', models.CharField(choices=[('DG', 'Demir Gapylar'), ('AG', 'Agaç Gapylar'), ('MB', 'Mebeller'), ('DO', 'Demir Önümler'), ('BK', 'Beýlekiler')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slide1', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt1')),
                ('img_slide2', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt2')),
                ('img_slide3', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt3')),
                ('img_slide4', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt4')),
                ('img_slide5', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt5')),
                ('img_slide6', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Slayt6')),
                ('text_slide1', models.CharField(max_length=32)),
                ('text_slide2', models.CharField(max_length=32)),
                ('text_slide3', models.CharField(max_length=32)),
                ('text_slide4', models.CharField(max_length=32)),
                ('text_slide5', models.CharField(max_length=32)),
                ('text_slide6', models.CharField(max_length=32)),
                ('description_slide1', models.TextField(verbose_name='Giňişleýin')),
                ('description_slide2', models.TextField(verbose_name='Giňişleýin')),
                ('description_slide3', models.TextField(verbose_name='Giňişleýin')),
                ('description_slide4', models.TextField(verbose_name='Giňişleýin')),
                ('description_slide5', models.TextField(verbose_name='Giňişleýin')),
                ('description_slide6', models.TextField(verbose_name='Giňişleýin')),
                ('company_name', models.CharField(max_length=64)),
                ('about_company', models.TextField(verbose_name='Kärhana Barada Giňişleýin')),
                ('property1', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon')),
                ('property2', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon')),
                ('property3', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon')),
                ('text_property1', models.TextField(verbose_name='Hyzmat1')),
                ('text_property2', models.TextField(verbose_name='Hyzmat2')),
                ('text_property3', models.TextField(verbose_name='Hyzmat3')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Haryt Suraty')),
                ('product_description', models.TextField(verbose_name='Haryt Barada Giňişleýin')),
                ('is_new', models.BooleanField(default=0)),
                ('product_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furnitures.Group', verbose_name='Görnüşi')),
            ],
        ),
    ]
