# Generated by Django 2.2.9 on 2020-01-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Haryt Suraty'),
        ),
    ]
