# Generated by Django 2.2.9 on 2020-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_auto_20200125_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_page',
            name='description_slide1',
            field=models.TextField(verbose_name='Slayt1 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide2',
            field=models.TextField(verbose_name='Slayt2 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide3',
            field=models.TextField(verbose_name='Slayt3 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide4',
            field=models.TextField(verbose_name='Slayt4 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide5',
            field=models.TextField(verbose_name='Slayt5 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='description_slide6',
            field=models.TextField(verbose_name='Slayt6 Giňişleýin'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide1',
            field=models.CharField(max_length=32, verbose_name='Slayt1 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide2',
            field=models.CharField(max_length=32, verbose_name='Slayt2 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide3',
            field=models.CharField(max_length=32, verbose_name='Slayt3 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide4',
            field=models.CharField(max_length=32, verbose_name='Slayt4 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide5',
            field=models.CharField(max_length=32, verbose_name='Slayt5 tekst'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='text_slide6',
            field=models.CharField(max_length=32, verbose_name='Slayt6 tekst'),
        ),
    ]
