# Generated by Django 2.2.9 on 2020-01-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0003_auto_20200127_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=128, verbose_name='Gruppanyn ady'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('DG', 'Demir Gapylar'), ('AG', 'Agaç Gapylar'), ('MB', 'Mebeller'), ('DO', 'Demir Önümler'), ('BK', 'Beýlekiler')], max_length=2, verbose_name='Topary'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='company_name',
            field=models.CharField(max_length=64, verbose_name='Kärhananyň ady'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='property1',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon1'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='property2',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon2'),
        ),
        migrations.AlterField(
            model_name='main_page',
            name='property3',
            field=models.ImageField(default='default.jpg', upload_to='furnitures/images/', verbose_name='Icon3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=1, verbose_name='Täzemi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name='Haryt Barada Giňişleýin Maglumat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furnitures.Group', verbose_name='Gruppasy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=128, verbose_name='Harydyň ady'),
        ),
    ]
